import { useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, Download, FileText, Printer, TrendingDown, TrendingUp } from 'lucide-react';
import { useInventory } from '../context/InventoryContext';
import { currency, downloadCsv, formatDate, getStockStatus, number, stockLabel } from '../lib/utils';
import { Badge, Button, Card, EmptyState, PageHeader, ProductThumb, Select } from '../components/ui';

type ReportTab = 'inventory' | 'movement' | 'low-stock';

export function ReportsPage() {
  const { data, notify } = useInventory();
  const [tab, setTab] = useState<ReportTab>('inventory');
  const [range, setRange] = useState('30');
  const products = data.products.filter((product) => product.status === 'active');
  const lowStock = products.filter((product) => getStockStatus(product) !== 'in-stock').sort((a, b) => a.quantity - b.quantity);
  const transactions = useMemo(() => {
    if (range === 'all') return data.transactions;
    const start = new Date(); start.setDate(start.getDate() - Number(range)); start.setHours(0, 0, 0, 0);
    return data.transactions.filter((item) => new Date(item.createdAt) >= start);
  }, [data.transactions, range]);
  const inventoryValue = products.reduce((sum, product) => sum + product.quantity * product.cost, 0);
  const retailValue = products.reduce((sum, product) => sum + product.quantity * product.sellingPrice, 0);
  const inbound = transactions.filter((item) => item.type === 'stock-in').reduce((sum, item) => sum + item.quantity, 0);
  const outbound = transactions.filter((item) => item.type === 'stock-out').reduce((sum, item) => sum + item.quantity, 0);

  const exportReport = () => {
    if (tab === 'inventory') downloadCsv('current-inventory.csv', [['SKU', 'Barcode', 'Product', 'Category', 'Supplier', 'Quantity', 'Reorder level', 'Unit cost', 'Retail price', 'Stock value'], ...products.map((product) => [product.sku, product.barcode, product.name, data.categories.find((item) => item.id === product.categoryId)?.name ?? '', data.suppliers.find((item) => item.id === product.supplierId)?.name ?? '', product.quantity, product.reorderLevel, product.cost, product.sellingPrice, product.quantity * product.cost])]);
    if (tab === 'movement') downloadCsv('stock-movement.csv', [['Date', 'Reference', 'Type', 'Product', 'SKU', 'Quantity', 'Previous stock', 'New stock', 'Performed by', 'Note'], ...transactions.map((item) => { const product = products.find((product) => product.id === item.productId); return [item.createdAt, item.reference, item.type, product?.name ?? '', product?.sku ?? '', item.quantity, item.previousStock, item.newStock, data.users.find((user) => user.id === item.performedBy)?.name ?? '', item.note]; })]);
    if (tab === 'low-stock') downloadCsv('low-stock-products.csv', [['SKU', 'Product', 'Quantity', 'Reorder level', 'Shortfall', 'Supplier'], ...lowStock.map((product) => [product.sku, product.name, product.quantity, product.reorderLevel, Math.max(0, product.reorderLevel - product.quantity), data.suppliers.find((item) => item.id === product.supplierId)?.name ?? ''])]);
    notify('success', 'CSV report exported', 'Your file is ready in the browser downloads folder.');
  };

  return <div className="animate-enter"><PageHeader eyebrow="Analytics" title="Inventory reports" description="Review inventory position, product movement, and replenishment priorities." actions={<><Button variant="secondary" onClick={() => window.print()} className="no-print"><Printer size={17} />Print / PDF</Button><Button onClick={exportReport} className="no-print"><Download size={17} />Export CSV</Button></>} />
    <div className="no-print mb-5 flex flex-col justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-2 shadow-card sm:flex-row sm:items-center"><div className="grid grid-cols-3 gap-1">{([{ id: 'inventory', label: 'Current inventory', icon: FileText }, { id: 'movement', label: 'Stock movement', icon: BarChart3 }, { id: 'low-stock', label: 'Low stock', icon: AlertTriangle }] as const).map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex h-10 items-center justify-center gap-2 rounded-xl px-3 text-xs font-bold transition sm:text-sm ${tab === id ? 'bg-brand-600 text-white shadow-sm' : 'text-slate-500 hover:bg-slate-50'}`}><Icon size={15} /><span className="hidden sm:inline">{label}</span></button>)}</div>{tab === 'movement' && <Select value={range} onChange={(event) => setRange(event.target.value)} className="sm:w-44"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="all">All time</option></Select>}</div>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{tab === 'inventory' && <><Metric label="Inventory cost value" value={currency(inventoryValue)} icon={<FileText />} tone="blue" /><Metric label="Potential retail value" value={currency(retailValue)} icon={<TrendingUp />} tone="green" /><Metric label="Potential gross margin" value={currency(retailValue - inventoryValue)} icon={<BarChart3 />} tone="purple" /><Metric label="Units on hand" value={number(products.reduce((sum, item) => sum + item.quantity, 0))} icon={<BarChart3 />} tone="slate" /></>}{tab === 'movement' && <><Metric label="Transactions" value={number(transactions.length)} icon={<FileText />} tone="blue" /><Metric label="Units received" value={`+${number(inbound)}`} icon={<TrendingUp />} tone="green" /><Metric label="Units issued" value={`−${number(outbound)}`} icon={<TrendingDown />} tone="amber" /><Metric label="Net change" value={`${inbound - outbound >= 0 ? '+' : ''}${number(inbound - outbound)}`} icon={<BarChart3 />} tone="purple" /></>}{tab === 'low-stock' && <><Metric label="Needs attention" value={number(lowStock.length)} icon={<AlertTriangle />} tone="amber" /><Metric label="Out of stock" value={number(lowStock.filter((item) => item.quantity === 0).length)} icon={<TrendingDown />} tone="red" /><Metric label="Units to reorder" value={number(lowStock.reduce((sum, item) => sum + Math.max(0, item.reorderLevel - item.quantity), 0))} icon={<TrendingUp />} tone="blue" /><Metric label="Estimated reorder cost" value={currency(lowStock.reduce((sum, item) => sum + Math.max(0, item.reorderLevel - item.quantity) * item.cost, 0))} icon={<FileText />} tone="purple" /></>}</div>
    <Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-display text-lg font-extrabold text-ink">{tab === 'inventory' ? 'Current inventory report' : tab === 'movement' ? 'Stock movement report' : 'Low-stock report'}</h2><p className="mt-1 text-xs text-slate-500">Generated {new Intl.DateTimeFormat('en-US', { dateStyle: 'long', timeStyle: 'short' }).format(new Date())}</p></div>
      {tab === 'inventory' && <div className="table-scroll"><table><thead><tr><th>Product</th><th>Category</th><th>On hand</th><th>Status</th><th>Unit cost</th><th>Stock value</th><th>Retail value</th></tr></thead><tbody>{products.map((product) => { const status = getStockStatus(product); return <tr key={product.id}><td><div className="flex min-w-[220px] items-center gap-3"><ProductThumb image={product.image} name={product.name} size="sm" /><div><p className="font-bold text-slate-800">{product.name}</p><p className="text-xs text-slate-400">{product.sku}</p></div></div></td><td className="whitespace-nowrap text-slate-600">{data.categories.find((item) => item.id === product.categoryId)?.name}</td><td className="font-bold text-slate-800">{product.quantity}</td><td><Badge tone={status === 'in-stock' ? 'green' : status === 'low-stock' ? 'amber' : 'red'}>{stockLabel[status]}</Badge></td><td className="font-semibold text-slate-600">{currency(product.cost)}</td><td className="font-bold text-slate-800">{currency(product.quantity * product.cost)}</td><td className="font-semibold text-slate-600">{currency(product.quantity * product.sellingPrice)}</td></tr>; })}</tbody></table></div>}
      {tab === 'movement' && (transactions.length ? <div className="table-scroll"><table><thead><tr><th>Date</th><th>Reference</th><th>Product</th><th>Movement</th><th>Before</th><th>After</th><th>User</th></tr></thead><tbody>{transactions.map((transaction) => { const product = data.products.find((item) => item.id === transaction.productId); return <tr key={transaction.id}><td className="whitespace-nowrap font-semibold text-slate-600">{formatDate(transaction.createdAt, true)}</td><td className="font-mono text-xs font-bold text-slate-600">{transaction.reference}</td><td><p className="min-w-[200px] font-bold text-slate-800">{product?.name}</p><p className="text-xs text-slate-400">{product?.sku}</p></td><td><Badge tone={transaction.type === 'stock-in' ? 'green' : 'amber'}>{transaction.type === 'stock-in' ? '+' : '−'}{transaction.quantity} units</Badge></td><td className="text-slate-500">{transaction.previousStock}</td><td className="font-bold text-slate-800">{transaction.newStock}</td><td className="whitespace-nowrap text-slate-600">{data.users.find((item) => item.id === transaction.performedBy)?.name}</td></tr>; })}</tbody></table></div> : <EmptyState title="No movement in this period" description="Choose a wider reporting period or record a stock transaction." />)}
      {tab === 'low-stock' && (lowStock.length ? <div className="table-scroll"><table><thead><tr><th>Priority</th><th>Product</th><th>Supplier</th><th>On hand</th><th>Reorder level</th><th>Shortfall</th><th>Reorder estimate</th></tr></thead><tbody>{lowStock.map((product) => { const shortfall = Math.max(0, product.reorderLevel - product.quantity); return <tr key={product.id}><td><Badge tone={product.quantity === 0 ? 'red' : 'amber'}>{product.quantity === 0 ? 'Critical' : 'Reorder'}</Badge></td><td><div className="flex min-w-[220px] items-center gap-3"><ProductThumb image={product.image} name={product.name} size="sm" /><div><p className="font-bold text-slate-800">{product.name}</p><p className="text-xs text-slate-400">{product.sku}</p></div></div></td><td className="whitespace-nowrap text-slate-600">{data.suppliers.find((item) => item.id === product.supplierId)?.name}</td><td className="font-display text-base font-extrabold text-slate-800">{product.quantity}</td><td className="text-slate-600">{product.reorderLevel}</td><td className="font-bold text-red-600">{shortfall} units</td><td className="font-semibold text-slate-700">{currency(shortfall * product.cost)}</td></tr>; })}</tbody></table></div> : <EmptyState title="Stock levels are healthy" description="No active products are currently at or below their reorder level." />)}
    </Card>
  </div>;
}

function Metric({ label, value, icon, tone }: { label: string; value: string; icon: React.ReactNode; tone: 'blue' | 'green' | 'amber' | 'purple' | 'red' | 'slate' }) {
  const styles = { blue: 'bg-blue-50 text-blue-600', green: 'bg-emerald-50 text-emerald-600', amber: 'bg-amber-50 text-amber-600', purple: 'bg-violet-50 text-violet-600', red: 'bg-red-50 text-red-600', slate: 'bg-slate-100 text-slate-600' };
  return <Card className="flex items-center gap-4 p-4"><div className={`grid h-11 w-11 place-items-center rounded-xl [&>svg]:h-5 [&>svg]:w-5 ${styles[tone]}`}>{icon}</div><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-0.5 font-display text-xl font-extrabold text-ink">{value}</p></div></Card>;
}
