import { useMemo, useState } from 'react';
import { Building2, Mail, MapPin, Pencil, Phone, Plus, Power, Truck } from 'lucide-react';
import { useInventory } from '../context/InventoryContext';
import { canManageCatalog } from '../services/inventoryService';
import type { Supplier, SupplierInput } from '../types';
import { Badge, Button, Card, ConfirmDialog, EmptyState, FormField, Input, Modal, PageHeader, SearchInput, Select } from '../components/ui';

const blankSupplier: SupplierInput = { name: '', contactName: '', email: '', phone: '', address: '', status: 'active' };

function SupplierForm({ supplier, onClose }: { supplier?: Supplier; onClose(): void }) {
  const { saveSupplier } = useInventory();
  const [form, setForm] = useState<SupplierInput>(supplier ? { name: supplier.name, contactName: supplier.contactName, email: supplier.email, phone: supplier.phone, address: supplier.address, status: supplier.status } : blankSupplier);
  const [error, setError] = useState('');
  const set = (field: keyof SupplierInput, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); setError(''); try { saveSupplier(form, supplier?.id); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save this supplier.'); } };
  return <form id="supplier-form" onSubmit={submit} className="space-y-4">{error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}<div className="grid gap-4 sm:grid-cols-2"><FormField label="Company name" required className="sm:col-span-2"><Input value={form.name} onChange={(event) => set('name', event.target.value)} placeholder="Supplier company" autoFocus required /></FormField><FormField label="Contact person" required><Input value={form.contactName} onChange={(event) => set('contactName', event.target.value)} placeholder="Full name" required /></FormField><FormField label="Status"><Select value={form.status} onChange={(event) => set('status', event.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></Select></FormField><FormField label="Email address" required><Input type="email" value={form.email} onChange={(event) => set('email', event.target.value)} placeholder="orders@company.com" required /></FormField><FormField label="Phone number"><Input value={form.phone} onChange={(event) => set('phone', event.target.value)} placeholder="+1 (555) 000-0000" /></FormField><FormField label="Business address" className="sm:col-span-2"><Input value={form.address} onChange={(event) => set('address', event.target.value)} placeholder="Street, city, state" /></FormField></div></form>;
}

export function SuppliersPage() {
  const { data, user, toggleSupplier } = useInventory();
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('all');
  const [editing, setEditing] = useState<Supplier | 'new' | null>(null);
  const [toggling, setToggling] = useState<Supplier | null>(null);
  const canManage = !!user && canManageCatalog(user.role);
  const filtered = useMemo(() => data.suppliers.filter((supplier) => {
    const term = search.toLowerCase();
    return (status === 'all' || supplier.status === status) && (!term || [supplier.name, supplier.contactName, supplier.email].some((value) => value.toLowerCase().includes(term)));
  }), [data.suppliers, search, status]);
  const active = data.suppliers.filter((item) => item.status === 'active').length;
  const productsSourced = data.products.filter((item) => item.status === 'active').length;

  return <div className="animate-enter"><PageHeader eyebrow="Procurement" title="Suppliers" description="Maintain your vendor directory and see the products connected to every supplier." actions={canManage ? <Button onClick={() => setEditing('new')}><Plus size={17} />Add supplier</Button> : <Badge tone="slate">View-only access</Badge>} />
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><Card className="flex items-center gap-4 p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-brand-600"><Building2 size={20} /></div><div><p className="text-xs font-semibold text-slate-500">Total suppliers</p><p className="font-display text-xl font-extrabold">{data.suppliers.length}</p></div></Card><Card className="flex items-center gap-4 p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><Truck size={20} /></div><div><p className="text-xs font-semibold text-slate-500">Active partners</p><p className="font-display text-xl font-extrabold">{active}</p></div></Card><Card className="flex items-center gap-4 p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-violet-50 text-violet-600"><Building2 size={20} /></div><div><p className="text-xs font-semibold text-slate-500">Products sourced</p><p className="font-display text-xl font-extrabold">{productsSourced}</p></div></Card></div>
    <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:p-5"><SearchInput value={search} onChange={setSearch} placeholder="Search supplier, contact, or email…" /><Select value={status} onChange={(event) => setStatus(event.target.value)} className="sm:w-40"><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></Select></div>{filtered.length ? <div className="table-scroll"><table><thead><tr><th>Supplier</th><th>Primary contact</th><th>Contact details</th><th>Location</th><th>Products</th><th>Status</th><th className="text-right">Actions</th></tr></thead><tbody>{filtered.map((supplier) => { const productCount = data.products.filter((item) => item.supplierId === supplier.id && item.status === 'active').length; return <tr key={supplier.id}><td><div className="flex min-w-[190px] items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 font-display text-sm font-extrabold text-slate-600">{supplier.name.split(' ').map((word) => word[0]).slice(0, 2).join('')}</div><p className="font-bold text-slate-800">{supplier.name}</p></div></td><td className="whitespace-nowrap font-semibold text-slate-600">{supplier.contactName}</td><td><div className="min-w-[220px] space-y-1"><a href={`mailto:${supplier.email}`} className="flex items-center gap-2 text-xs text-slate-600 hover:text-brand-600"><Mail size={13} />{supplier.email}</a><p className="flex items-center gap-2 text-xs text-slate-500"><Phone size={13} />{supplier.phone || 'Not provided'}</p></div></td><td><p className="flex min-w-[180px] items-start gap-2 text-xs leading-5 text-slate-500"><MapPin size={13} className="mt-0.5 shrink-0" />{supplier.address || 'Not provided'}</p></td><td><Badge tone="blue">{productCount} products</Badge></td><td><Badge tone={supplier.status === 'active' ? 'green' : 'slate'}>{supplier.status}</Badge></td><td><div className="flex justify-end gap-1">{canManage && <><button onClick={() => setEditing(supplier)} className="grid h-9 w-9 place-items-center rounded-lg text-slate-400 hover:bg-blue-50 hover:text-brand-600" title="Edit supplier"><Pencil size={16} /></button><button onClick={() => setToggling(supplier)} className="grid h-9 w-9 place-items-center rounded-lg text-slate-400 hover:bg-amber-50 hover:text-amber-600" title="Change status"><Power size={16} /></button></>}</div></td></tr>; })}</tbody></table></div> : <EmptyState title="No suppliers found" description="Try a different search or add a supplier to your vendor directory." action={canManage ? <Button onClick={() => setEditing('new')}><Plus size={17} />Add supplier</Button> : undefined} />}</Card>
    <Modal open={!!editing} onClose={() => setEditing(null)} title={editing === 'new' ? 'Add supplier' : 'Edit supplier'} description="Keep vendor contact and status information current." footer={<><Button variant="secondary" onClick={() => setEditing(null)}>Cancel</Button><Button type="submit" form="supplier-form">{editing === 'new' ? 'Create supplier' : 'Save changes'}</Button></>}>{editing && <SupplierForm supplier={editing === 'new' ? undefined : editing} onClose={() => setEditing(null)} />}</Modal>
    <ConfirmDialog open={!!toggling} onClose={() => setToggling(null)} onConfirm={() => toggling && toggleSupplier(toggling.id)} title={`${toggling?.status === 'active' ? 'Deactivate' : 'Activate'} supplier?`} description={toggling?.status === 'active' ? `${toggling?.name} will remain linked to products but will not appear as an active option for new records.` : `${toggling?.name} will be available for new product records.`} confirmLabel={toggling?.status === 'active' ? 'Deactivate' : 'Activate'} danger={toggling?.status === 'active'} />
  </div>;
}
