import type { ReactNode } from 'react';
import { Boxes, CheckCircle2, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';

export function AuthShell({ eyebrow, title, description, children, footer }: { eyebrow: string; title: string; description: string; children: ReactNode; footer: ReactNode }) {
  return <div className="min-h-screen bg-slate-950 lg:grid lg:grid-cols-[minmax(380px,.8fr)_minmax(520px,1.2fr)]">
    <aside className="relative hidden overflow-hidden p-12 lg:flex lg:flex-col"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_0%,rgba(37,99,235,.3),transparent_38%),radial-gradient(circle_at_80%_90%,rgba(124,58,237,.2),transparent_40%)]" /><Link to="/login" className="relative z-10 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-brand-600 text-white shadow-lg shadow-brand-900/50"><Boxes size={24} /></span><div><p className="font-display text-xl font-extrabold text-white">StockPilot</p><p className="text-[10px] font-bold uppercase tracking-[.2em] text-slate-500">Inventory OS</p></div></Link><div className="relative z-10 my-auto"><h2 className="max-w-lg font-display text-4xl font-extrabold leading-tight tracking-tight text-white">One workspace.<br /><span className="text-brand-400">Every inventory move.</span></h2><div className="mt-9 space-y-4">{['Secure role-based access', 'Real-time inventory visibility', 'Complete action history'].map((item) => <div key={item} className="flex items-center gap-3 text-sm font-semibold text-slate-300"><span className="grid h-7 w-7 place-items-center rounded-lg bg-emerald-400/10 text-emerald-400"><CheckCircle2 size={15} /></span>{item}</div>)}</div></div><p className="relative z-10 flex items-center gap-2 text-xs text-slate-600"><ShieldCheck size={14} />Protected StockPilot workspace</p></aside>
    <main className="flex min-h-screen items-center justify-center bg-canvas px-5 py-10 sm:px-10"><div className="w-full max-w-lg animate-enter"><Link to="/login" className="mb-8 flex items-center gap-3 lg:hidden"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-600 text-white"><Boxes size={21} /></span><span className="font-display text-xl font-extrabold text-ink">StockPilot</span></Link><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600">{eyebrow}</p><h1 className="mt-2 font-display text-3xl font-extrabold tracking-tight text-ink">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><div className="mt-7">{children}</div><div className="mt-6 border-t border-slate-100 pt-5 text-center text-sm text-slate-500">{footer}</div></div></div></main>
  </div>;
}
